name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: '1.22'

    - name: Build all
      run: make all

    - name: Create Tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release binaries
      uses: "ncipollo/release-action@v1"
      with:
        artifacts: "bin/**/*"
        name: "Saug mich ${{ steps.tag.outputs.new_tag }}"
        tag: ${{ steps.tag.outputs.new_tag }}
        allowUpdates: true 

